name: Django

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies and run Django check
        run: |
          python -m pip install --upgrade pip virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt
          echo "===> Checking Django configuration"
          python manage.py check || (echo "❌ manage.py check failed" && exit 1)

  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies and run tests
        run: |
          python -m pip install --upgrade pip virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt
          echo "===> Running tests"
          python manage.py test taskManager || (echo "❌ Tests failed" && exit 1)

  oast:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Run Safety scan inside Docker
        run: |
          echo "===> Running Safety scan"
          docker run --rm -v $(pwd):/src hysnsec/safety check -r requirements.txt --json > oast-results.json || echo "❌ Safety scan failed, continuing anyway"
        continue-on-error: true

      - name: Upload Safety scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Safety
          path: oast-results.json

  integration:
    runs-on: ubuntu-22.04
    needs: oast
    steps:
      - name: Run integration step
        run: echo "This is an integration step"

      - name: Simulated optional step
        run: exit 0
        continue-on-error: true

  prod:
    runs-on: ubuntu-22.04
    needs: integration
    steps:
      - name: Deploy
        run: echo "This is a deploy step."
